import svgPaths from './svg-wj4geuf9e4'
// interface Web3ProfileCardProps {
//     verificationTick?: boolean;
// }
function Web3ProfileCard(/*{ verificationTick = true }: Web3ProfileCardProps*/) {
    return (<div className="relative rounded-[28px] size-full" data-name="web3_profile_card"><div className="box-border content-stretch flex flex-col items-center justify-start overflow-clip p-0 relative size-full"><div className="relative shrink-0 w-full" data-name="all_inputs"><div className="relative size-full"><div className="box-border content-stretch flex flex-row items-start justify-between p-[20px] relative w-full"><div className="basis-0 box-border content-stretch flex flex-row gap-4 grow items-center justify-start min-h-px min-w-px p-0 relative shrink-0" data-name="profile"><div className="basis-0 box-border content-stretch flex flex-col gap-1 grow items-start justify-start min-h-px min-w-px p-0 relative shrink-0" data-name="details"><div className="box-border content-stretch flex flex-row gap-1.5 items-center justify-start p-0 relative shrink-0 w-full" data-name="name"><div className="font-['Open_Sauce_Two:SemiBold',_sans-serif] leading-[0] not-italic relative shrink-0 text-[#ffffff] text-[18px] text-left text-nowrap"><p className="block leading-[24px] whitespace-pre">akashtyagi.eth</p></div></div></div></div></div></div></div><div className="relative shrink-0 w-full" data-name="setting"><div aria-hidden="true" className="absolute border-[1px_0px_0px] border-[rgba(255,255,255,0)] border-solid inset-0 pointer-events-none"/><div className="relative size-full"><div className="box-border content-stretch flex flex-col gap-4 items-start justify-start pb-6 pt-4 px-5 relative w-full"><div className="box-border content-stretch flex flex-col gap-1 items-start justify-start p-0 relative shrink-0 w-full" data-name="details"><div className="font-['Open_Sauce_Two:SemiBold',_sans-serif] leading-[0] not-italic relative shrink-0 text-[11px] text-[rgba(255,255,255,0.48)] text-left uppercase w-full"><p className="block leading-[16px]">Your fPass address</p></div><div className="box-border content-stretch flex flex-row gap-3 items-center justify-start p-0 relative shrink-0 w-full" data-name="header"><div className="basis-0 font-['Open_Sauce_Two:SemiBold',_sans-serif] grow leading-[0] min-h-px min-w-px not-italic relative shrink-0 text-[#ffffff] text-[22px] text-left"><p className="block leading-[32px]">0x7eE7...9F27</p></div><div className="box-border content-stretch flex flex-row gap-1 items-center justify-center overflow-clip px-1.5 py-1 relative rounded-md shrink-0 size-6" data-name="icon_button">{ ( (<div className="relative shrink-0 size-4" data-name="icon"><div className="absolute inset-[8.33%_12.5%_8.63%_12.5%]" data-name="Union"><svg className="block size-full" fill="none" preserveAspectRatio="none" role="presentation" viewBox="0 0 12 14">
        <g id="Union">
        <path d={svgPaths.p31610a80} fill="var(--fill-0, white)" fillOpacity="0.72"/>
        <path d={svgPaths.p36946880} fill="var(--fill-0, white)" fillOpacity="0.72"/>
        </g>
        </svg></div></div>))}</div></div></div><div className="box-border content-stretch flex flex-col gap-1 items-start justify-start p-0 relative shrink-0 w-full" data-name="details"><div className="font-['Open_Sauce_Two:SemiBold',_sans-serif] leading-[0] not-italic relative shrink-0 text-[11px] text-[rgba(255,255,255,0.48)] text-left uppercase w-full"><p className="block leading-[16px]">Signed in with non-custodial wallet</p></div><div className="box-border content-stretch flex flex-row gap-3 items-center justify-start p-0 relative shrink-0 w-full" data-name="header"><div className="basis-0 font-['Open_Sauce_Two:SemiBold',_sans-serif] grow leading-[0] min-h-px min-w-px not-italic relative shrink-0 text-[#ffffff] text-[22px] text-left"><p className="block leading-[32px]">0x7eE7...9F27</p></div><div className="box-border content-stretch flex flex-row gap-1 items-center justify-center overflow-clip px-1.5 py-1 relative rounded-md shrink-0 size-6" data-name="icon_button">{ (  (<div className="relative shrink-0 size-4" data-name="icon"><div className="absolute inset-[8.33%_12.5%_8.63%_12.5%]" data-name="Union"><svg className="block size-full" fill="none" preserveAspectRatio="none" role="presentation" viewBox="0 0 12 14">
        <g id="Union">
        <path d={svgPaths.p31610a80} fill="var(--fill-0, white)" fillOpacity="0.72"/>
        <path d={svgPaths.p36946880} fill="var(--fill-0, white)" fillOpacity="0.72"/>
        </g>
        </svg></div></div>))}</div></div></div><div className="box-border content-stretch flex flex-row gap-2 items-start justify-start p-0 relative shrink-0 w-full" data-name="actions"><div className="basis-0 bg-[#141414] grow h-10 min-h-px min-w-px relative rounded-[10px] shrink-0" data-name="button"><div className="flex flex-row items-center justify-center overflow-clip relative size-full"><div className="box-border content-stretch flex flex-row gap-2 h-10 items-center justify-center px-3 py-2 relative w-full">{ (<div className="font-['Open_Sauce_Two:SemiBold',_sans-serif] leading-[0] not-italic relative shrink-0 text-[13px] text-[rgba(255,255,255,0.72)] text-left text-nowrap"><p className="block leading-[24px] whitespace-pre">Disconnect Wallet</p></div>)}</div></div><div aria-hidden="true" className="absolute border border-[rgba(255,255,255,0.04)] border-solid inset-0 pointer-events-none rounded-[10px]"/></div></div></div></div></div></div><div aria-hidden="true" className="absolute border border-[#8d7aff] border-solid inset-0 pointer-events-none rounded-[28px] shadow-[0px_1px_1px_-0.5px_rgba(0,0,0,0.12),0px_3px_3px_-1.5px_rgba(0,0,0,0.12),0px_6px_6px_-3px_rgba(0,0,0,0.12),0px_32px_32px_-16px_rgba(0,0,0,0.12),0px_56px_56px_-28px_rgba(0,0,0,0.12)]"/></div>);
}
export default function Web3ProfileCard1() {
    return <div className="bg-[#070707] relative rounded-[28px] size-full" data-name="web3_profile_card"><Web3ProfileCard /></div>;
}
