import type { Metadata } from "next";
import "./globals.css";
import {QueryProvider} from "@/context";
// import {Providers} from "@/context/Providers";
// import {QueryProvider} from "@/context/QueryProvider";


export const metadata: Metadata = {
  title: "TRN Governance V1 Application",
  description: "Generated by create next app",
};

//<body className={poppins.className}>
// 				<Providers>
// 					<Container>
// 						<DisableMobileProvider>{children}</DisableMobileProvider>
// 					</Container>
// 				</Providers>
// 			</body>
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

    <body>
    <QueryProvider>
      <div id="root">{children}</div>
       {/*<script type="module" src="/src/main.tsx"></script>*/}
    </QueryProvider>
    </body>
   </html>
  );
}
